# Generated by Django 3.2.7 on 2021-09-20 17:49

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'هه\u200cژمار',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='هاتوو')),
                ('loan', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='دەرچووو')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ناوی مەواد')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[400, 400], upload_to='images/', verbose_name='وێنه\u200c')),
                ('deleted', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='ریكه\u200cوتی دانان')),
            ],
            options={
                'verbose_name_plural': 'جۆره\u200cكانی خواردن',
            },
        ),
        migrations.CreateModel(
            name='Dliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=110, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('phoneId', models.CharField(blank=True, max_length=110, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[200, 200], upload_to='images/', verbose_name='وێنه\u200c')),
            ],
            options={
                'verbose_name_plural': 'شۆفێر',
            },
        ),
        migrations.CreateModel(
            name='Epmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ناوی کرێکار')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='ژ.موبایل')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[300, 300], upload_to='images/', verbose_name='وێنه\u200c')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='رێکەوت')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'کارمەندان',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ناوی بنکە')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='ژ.موبایل')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[300, 300], upload_to='images/', verbose_name='وێنه\u200c')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='رێکەوت')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'بنکەکان',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ناوی مەواد')),
                ('bag', models.CharField(max_length=250, verbose_name='جۆری مەواد')),
                ('wight', models.DecimalField(decimal_places=2, default='0.0', max_digits=22, verbose_name='کێشی کاڵا')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='نرخی کڕین')),
                ('addprice', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='رءژەی قازانژ')),
                ('quantity', models.IntegerField(verbose_name='dane')),
                ('barcode', models.CharField(max_length=150, verbose_name='کۆدی مەواد')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[400, 400], upload_to='images/', verbose_name='وێنه\u200c')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='رێکەوت')),
                ('deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='myapp.cat')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_group', to='myapp.group', verbose_name='ناوی بنکە')),
            ],
            options={
                'verbose_name_plural': 'کاڵاکان',
            },
        ),
        migrations.CreateModel(
            name='LocalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ناوی کڕیار')),
                ('code', models.CharField(max_length=150, verbose_name='کۆدی کڕیار')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='ناونیشان')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='ژ.موبایل')),
                ('owner_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ناوی خاوەنکار')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('exchange', models.DecimalField(decimal_places=2, default='0.0', max_digits=22, verbose_name='قەرزی یەکەمجار')),
                ('location', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[300, 300], upload_to='images/', verbose_name='وێنه\u200c')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='رێکەوت')),
                ('status', models.BooleanField(default=False)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'کڕیارەکان',
            },
        ),
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=110, null=True)),
                ('number', models.CharField(blank=True, max_length=11, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[300, 300], upload_to='images/', verbose_name='وێنه\u200c')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Motors',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=250, verbose_name='ژمارەی وەسڵ')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default='0.0', max_digits=22, verbose_name='داشکاندن')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_group', to='myapp.group', verbose_name='ناوی بنکە')),
            ],
            options={
                'verbose_name_plural': 'کڕین',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ناوچە')),
                ('code', models.CharField(max_length=150, verbose_name='کۆدی ناوچە')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[300, 300], upload_to='images/', verbose_name='وێنه\u200c')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='رێکەوت')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'ناوچەکان',
            },
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=11)),
                ('price', models.CharField(max_length=11)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='last edit')),
                ('status', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_item', to='myapp.item')),
            ],
            options={
                'verbose_name_plural': 'ورده\u200cكاری داواكاری',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, verbose_name='dashkan')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_group', to='myapp.group', verbose_name='ناوی بنکە')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_compnay', to='myapp.localcompany', verbose_name='کڕیار')),
            ],
            options={
                'verbose_name_plural': 'فرۆشتنەکان',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ناوی مەندوب')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='ژ.موبایل')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[300, 300], upload_to='images/', verbose_name='وێنه\u200c')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='رێکەوت')),
                ('status', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_group', to='myapp.group', verbose_name='ناو بنکە')),
                ('regions', models.ManyToManyField(to='myapp.Region')),
            ],
            options={
                'verbose_name_plural': 'فرۆشیاران-مەندوب',
            },
        ),
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VendosUser', to='myapp.account')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VendorUser', to='myapp.vendor')),
            ],
            options={
                'verbose_name_plural': 'مەندوب بەکارهێنەر',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('status', models.BooleanField(default=False)),
                ('dliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dliver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sell')),
            ],
            options={
                'verbose_name_plural': 'باركراو',
            },
        ),
        migrations.CreateModel(
            name='TradeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ناوی کۆمپانیا')),
                ('code', models.CharField(max_length=150, verbose_name='کۆدی کۆمپانیا یا ژ.موبایل')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('exchange', models.DecimalField(decimal_places=2, default='0.0', max_digits=22, verbose_name='qarz yakam jar')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[300, 300], upload_to='images/', verbose_name='وێنه\u200c')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='رێکەوت')),
                ('status', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader_group', to='myapp.group', verbose_name='ناوی بنکە')),
            ],
            options={
                'verbose_name_plural': 'کۆمپانیا',
            },
        ),
        migrations.CreateModel(
            name='SellDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='دانە')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='نرخ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sell', to='myapp.item', verbose_name='کاڵا')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_detail', to='myapp.sell', verbose_name='وەسڵ')),
            ],
            options={
                'verbose_name_plural': 'کاڵای دەرچوو',
            },
        ),
        migrations.AddField(
            model_name='sell',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_group', to='myapp.vendor', verbose_name='فرۆشیار'),
        ),
        migrations.CreateModel(
            name='ReSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='دانە')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='نرخ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReSell_item', to='myapp.item', verbose_name='کاڵا')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReSell_detail', to='myapp.sell', verbose_name='داواکاری')),
            ],
        ),
        migrations.CreateModel(
            name='RequestSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.CharField(max_length=11)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='last edit')),
                ('status', models.BooleanField(default=False)),
                ('local', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reqtlocal', to='myapp.localcompany')),
                ('request_detail', models.ManyToManyField(to='myapp.RequestDetail')),
            ],
            options={
                'verbose_name_plural': 'داواكاریه\u200cكان',
            },
        ),
        migrations.CreateModel(
            name='RequestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.CharField(max_length=11)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='last edit')),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reqtrader', to='myapp.tradecompany')),
                ('request_detail', models.ManyToManyField(to='myapp.RequestDetail')),
            ],
            options={
                'verbose_name_plural': 'داواكاریه\u200cكان',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='نرخی کڕین')),
                ('addprice', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='رءژەی قازانژ')),
                ('status', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_price', to='myapp.item')),
            ],
            options={
                'verbose_name_plural': 'نرخەکان',
            },
        ),
        migrations.CreateModel(
            name='Paysalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bank', to='myapp.bank', verbose_name='قاسە')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_employee', to='myapp.epmploye', verbose_name='کارمەند')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_group', to='myapp.group', verbose_name='ناوی بنکە')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_bank', to='myapp.bank', verbose_name='قاسە')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_group', to='myapp.group', verbose_name='ناوی بنکە')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_compnay', to='myapp.localcompany', verbose_name='کڕیار')),
            ],
            options={
                'verbose_name_plural': 'هه\u200cژمار',
            },
        ),
        migrations.CreateModel(
            name='Payloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_bank', to='myapp.bank', verbose_name='قاسە')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_group', to='myapp.group', verbose_name='ناوی بنکە')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_compnay', to='myapp.tradecompany', verbose_name='کڕیار')),
            ],
            options={
                'verbose_name_plural': 'هه\u200cژمار',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='dane')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='nrx')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='myapp.item', verbose_name='naw kala')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='myapp.order', verbose_name='wasl')),
            ],
            options={
                'verbose_name_plural': 'کالای هاتوو',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_compnay', to='myapp.tradecompany', verbose_name='کۆمپانیا'),
        ),
        migrations.AddField(
            model_name='localcompany',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_region', to='myapp.region', verbose_name='ناوچە'),
        ),
        migrations.AddField(
            model_name='item',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_compnay', to='myapp.tradecompany', verbose_name='کۆمپانیا'),
        ),
        migrations.AddField(
            model_name='dliver',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed_motor', to='myapp.motors'),
        ),
        migrations.AddField(
            model_name='dliver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account'),
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='هۆکار')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_bank', to='myapp.bank', verbose_name='قاسە')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_group', to='myapp.group', verbose_name='ناوی بنکە')),
            ],
        ),
        migrations.CreateModel(
            name='BnkaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('bnka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BnkaUser', to='myapp.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BnkasUser', to='myapp.account')),
            ],
            options={
                'verbose_name_plural': 'بنکەو بەکارهێنەر',
            },
        ),
        migrations.AddField(
            model_name='bank',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_group', to='myapp.group', verbose_name='ناوی بنکە'),
        ),
    ]
