# Generated by Django 3.2.7 on 2021-09-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nawy group')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nawy mawad')),
                ('bag', models.CharField(max_length=250, verbose_name='jor bar')),
                ('quantity', models.CharField(max_length=250, verbose_name='dane')),
                ('barcode', models.CharField(max_length=150, verbose_name='cody mewad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nrx kiren')),
                ('addprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='reje qazanc')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_group', to='myapp.group', verbose_name='naw group')),
            ],
        ),
        migrations.CreateModel(
            name='LocalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='naw kryar')),
                ('code', models.CharField(max_length=150, verbose_name='cody kryar')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='naw nishan')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='jmare mobile')),
                ('owner_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='naw xawenar')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_group', to='myapp.group', verbose_name='naw group')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nawche')),
                ('code', models.CharField(max_length=150, verbose_name='zip code')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='dashkan')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_group', to='myapp.group', verbose_name='naw group')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_compnay', to='myapp.localcompany', verbose_name='naw kryar')),
            ],
        ),
        migrations.CreateModel(
            name='TradeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='naw companya')),
                ('code', models.CharField(max_length=150, verbose_name='cody company')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('branch', models.CharField(blank=True, max_length=250, null=True, verbose_name='grwpy companya')),
            ],
        ),
        migrations.CreateModel(
            name='SellDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='dane')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nrx')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sell', to='myapp.item', verbose_name='naw kala')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_detail', to='myapp.sell', verbose_name='wasl')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=250, verbose_name='dane')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nrx')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='myapp.item', verbose_name='naw kala')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='myapp.order', verbose_name='wasl')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_compnay', to='myapp.tradecompany', verbose_name='naw compaya'),
        ),
        migrations.AddField(
            model_name='localcompany',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_region', to='myapp.region', verbose_name='nawche'),
        ),
        migrations.AddField(
            model_name='item',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_compnay', to='myapp.tradecompany', verbose_name='naw companyia'),
        ),
    ]
