# Generated by Django 3.2.7 on 2021-09-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='hawto')),
                ('loan', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='decho')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
            ],
        ),
        migrations.CreateModel(
            name='Epmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nawy krekar')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='jmary mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nawy group')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='jmary mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nawy mawad')),
                ('bag', models.CharField(max_length=250, verbose_name='jor bar')),
                ('wight', models.DecimalField(decimal_places=2, default='0.0', max_digits=22, verbose_name='wazn kala')),
                ('quantity', models.IntegerField(verbose_name='dane')),
                ('barcode', models.CharField(max_length=150, verbose_name='cody mewad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='nrx kiren')),
                ('addprice', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='reje qazanc')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_group', to='myapp.group', verbose_name='naw group')),
            ],
        ),
        migrations.CreateModel(
            name='LocalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='naw kryar')),
                ('code', models.CharField(max_length=150, verbose_name='cody kryar')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='naw nishan')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='jmare mobile')),
                ('owner_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='naw xawenar')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('exchange', models.DecimalField(decimal_places=2, default='0.0', max_digits=22, verbose_name='qarz yakam jar')),
                ('location', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=250, verbose_name='jamrey wesl')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default='0.0', max_digits=22, verbose_name='dashkandn')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_group', to='myapp.group', verbose_name='naw group')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nawche')),
                ('code', models.CharField(max_length=150, verbose_name='zip code')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, verbose_name='dashkan')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_group', to='myapp.group', verbose_name='naw group')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_compnay', to='myapp.localcompany', verbose_name='naw kryar')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nawy mandub')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='jmary mobile')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_group', to='myapp.group', verbose_name='naw group')),
                ('regions', models.ManyToManyField(to='myapp.Region')),
            ],
        ),
        migrations.CreateModel(
            name='TradeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='naw companya')),
                ('code', models.CharField(max_length=150, verbose_name='cody company')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('exchange', models.DecimalField(decimal_places=2, default='0.0', max_digits=22, verbose_name='qarz yakam jar')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader_group', to='myapp.group', verbose_name='naw group')),
            ],
        ),
        migrations.CreateModel(
            name='SellDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='dane')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='nrx')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sell', to='myapp.item', verbose_name='naw kala')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_detail', to='myapp.sell', verbose_name='wasl')),
            ],
        ),
        migrations.AddField(
            model_name='sell',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_group', to='myapp.vendor', verbose_name='naw mandub'),
        ),
        migrations.CreateModel(
            name='ReSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='dane')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='nrx')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReSell_item', to='myapp.item', verbose_name='naw kala')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReSell_detail', to='myapp.sell', verbose_name='wasl')),
            ],
        ),
        migrations.CreateModel(
            name='paysalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bank', to='myapp.bank', verbose_name='qase')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_employee', to='myapp.epmploye', verbose_name='krekar')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_group', to='myapp.group', verbose_name='naw group')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_bank', to='myapp.bank', verbose_name='qase')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_group', to='myapp.group', verbose_name='naw group')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_compnay', to='myapp.localcompany', verbose_name='naw kryar')),
            ],
        ),
        migrations.CreateModel(
            name='Payloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_bank', to='myapp.bank', verbose_name='qase')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_group', to='myapp.group', verbose_name='naw group')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_compnay', to='myapp.tradecompany', verbose_name='naw kryar')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='dane')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='nrx')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_order', to='myapp.item', verbose_name='naw kala')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='myapp.order', verbose_name='wasl')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_compnay', to='myapp.tradecompany', verbose_name='naw compaya'),
        ),
        migrations.AddField(
            model_name='localcompany',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_region', to='myapp.region', verbose_name='nawche'),
        ),
        migrations.AddField(
            model_name='item',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_compnay', to='myapp.tradecompany', verbose_name='naw companyia'),
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='barwar')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_bank', to='myapp.bank', verbose_name='qase')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_group', to='myapp.group', verbose_name='naw group')),
            ],
        ),
    ]
