# Generated by Django 3.2.7 on 2021-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradecompany',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ناونیشان'),
        ),
        migrations.AddField(
            model_name='tradecompany',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ژ.موبایل'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name=' دانە'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0, verbose_name=' مانەوەی یەکەم جار'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(verbose_name=' دانە'),
        ),
    ]
