# Generated by Django 3.2.7 on 2021-09-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_compnay', to='myapp.localcompany', verbose_name='naw kryar')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_compnay', to='myapp.tradecompany', verbose_name='naw compaya'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='myapp.order', verbose_name='wasl'),
        ),
        migrations.CreateModel(
            name='SellDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=250, verbose_name='dane')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nrx')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='rekwt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sell', to='myapp.item', verbose_name='naw kala')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_detail', to='myapp.sell', verbose_name='wasl')),
            ],
        ),
    ]
