# Generated by Django 3.2.7 on 2021-09-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='regions',
            field=models.ManyToManyField(to='myapp.Region'),
        ),
    ]
