# Generated by Django 3.2.7 on 2021-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='ho'),
        ),
    ]
