# Generated by Django 3.2.7 on 2022-02-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='request',
        ),
        migrations.AddField(
            model_name='transport',
            name='request',
            field=models.ManyToManyField(to='myapp.Sell'),
        ),
    ]
