# Generated by Django 3.2.7 on 2021-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selldetail',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
