# Generated by Django 3.2.7 on 2021-11-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payloan',
            options={'verbose_name_plural': 'قەرزدان'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'پارەدان'},
        ),
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selldetail',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='addprice',
            field=models.DecimalField(decimal_places=4, max_digits=22, verbose_name='رءژەی قازانژ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=22, verbose_name='نرخی کڕین'),
        ),
        migrations.AlterField(
            model_name='item',
            name='wight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='کێشی کاڵا'),
        ),
        migrations.CreateModel(
            name='OldAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='هاتوو')),
                ('loan', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='دەرچووو')),
                ('date', models.DateField(auto_now_add=True, verbose_name='بەروار')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='رێکەوت')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldacc_group', to='myapp.group', verbose_name='ناوی بنکە')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldacc_compnay', to='myapp.localcompany', verbose_name='کڕیار')),
            ],
            options={
                'verbose_name_plural': 'کۆن',
            },
        ),
    ]
