# Generated by Django 3.2.7 on 2021-09-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vendor_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_group', to='myapp.group', verbose_name='naw group'),
        ),
    ]
