# Generated by Django 3.2.7 on 2021-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210914_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldetail',
            name='quantity',
            field=models.IntegerField(verbose_name='dane'),
        ),
    ]
