# Generated by Django 3.2.7 on 2021-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_selldetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='dashkan'),
        ),
    ]
