# Generated by Django 3.2.7 on 2021-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vendor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wight',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, verbose_name='wazn kala'),
        ),
    ]
