# Generated by Django 3.2.7 on 2021-10-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_oldacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='addprice2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='رءژەی قازانژ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='wight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22, verbose_name='کێشی کاڵا'),
        ),
    ]
