# Generated by Django 3.2.7 on 2021-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sell_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='dashkan'),
        ),
    ]
