# Generated by Django 3.2.7 on 2021-09-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item_wight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='jamrey wesl'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.0', max_digits=5, verbose_name='dashkandn'),
        ),
    ]
