# Generated by Django 3.2.7 on 2021-10-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211016_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='addprice2',
        ),
    ]
